# Generated by Django 5.1.6 on 2025-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=100)),
                ('Rating', models.FloatField()),
                ('ReleaseDate', models.DateField()),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
    ]
